version: "3.9"
services:
  api:
    image: ghcr.io/kevinli8831/show-me-the-money-svc:latest
    container_name: show-me-the-money-svc
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.development                  # 直接讀你 repo 根目錄嘅 .env（超方便）